#!/usr/bin/env bash

if [[ ! -z $DOCKER_PRELOAD_IMAGES ]]; then
  preload-docker-images $DOCKER_PRELOAD_IMAGES &
fi;

if [[ -z $JENKINS_REMOTE_FS ]]; then
  JENKINS_REMOTE_FS=/ci/jenkins
fi;

echo "Getting slave.jar from ${JENKINS_URL}"
RESULT=-1
while [ true ]; do
 curl -s --url $JENKINS_URL/jnlpJars/jenkins-cli.jar --insecure --output jenkins-cli.jar
 RESULT=$?
 if [ $RESULT -eq 0 ]; then
     break
 else
     sleep 60
 fi
done
cat <<EOF | java -jar jenkins-cli.jar -s "$JENKINS_URL" -auth ${USER} create-node $JENKINS_AGENT_NAME
<slave>
     <name>${JENKINS_AGENT_NAME}</name>
     <description></description>
     <numExecutors>${EXECUTORS}</numExecutors>
     <mode>NORMAL</mode>
     <retentionStrategy class="hudson.slaves.RetentionStrategy\$Always"/>
     <launcher class="hudson.slaves.JNLPLauncher"/>
     <label>${LABELS}</label>
   <remoteFS>${JENKINS_REMOTE_FS}</remoteFS>
     <nodeProperties/>
   <userId>${USER}</userId>
</slave>
EOF

#Getting API Token
#JENKINS_SECRET="$(curl -s -u $USER $JENKINS_URL/computer/$JENKINS_AGENT_NAME/ | grep -Eo 'slave-agent.jnlp -secret ([a-z0-9]+)' | cut -d ' ' -f 3)"
JENKINS_SECRET="$(curl -L -s -u $USER  -X GET $JENKINS_URL/computer/$JENKINS_AGENT_NAME/slave-agent.jnlp | sed "s/.*<application-desc main-class=\"hudson.remoting.jnlp.Main\"><argument>\([a-z0-9]*\).*/\1/")"

if [ $# -eq 1 ]; then

    # if `docker run` only has one arguments, we assume user is running alternate command like `bash` to inspect the image
    exec "$@"

else

    # if -tunnel is not provided try env vars
    if [[ "$@" != *"-tunnel "* ]]; then
        if [ ! -z "$JENKINS_TUNNEL" ]; then
            TUNNEL="-tunnel $JENKINS_TUNNEL"
        fi
    fi

    if [ -n "$JENKINS_URL" ]; then
        URL="-url $JENKINS_URL"
    fi

    if [ -z "$JNLP_PROTOCOL_OPTS" ]; then
        echo "Warning: JnlpProtocol3 is disabled by default, use JNLP_PROTOCOL_OPTS to alter the behavior"
        JNLP_PROTOCOL_OPTS="-Dorg.jenkinsci.remoting.engine.JnlpProtocol3.disabled=true"
    fi

    exec java $JAVA_OPTS $JNLP_PROTOCOL_OPTS -cp /usr/share/jenkins/slave.jar hudson.remoting.jnlp.Main -headless $TUNNEL $URL $JENKINS_SECRET $JENKINS_AGENT_NAME "$@"
fi
